/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
title: (FREE) iPhone 13 Pro 2021
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Back: THREE.MeshStandardMaterial;
    GOLD: THREE.MeshStandardMaterial;
    BARRES: THREE.MeshStandardMaterial;
    Labber: THREE.MeshStandardMaterial;
    GLASS: THREE.MeshStandardMaterial;
    Lenscover: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Display: THREE.MeshStandardMaterial;
    ["Lens.2"]: THREE.MeshStandardMaterial;
    material_11: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/iphone.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.54}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.1, 1.45, -0.26]} scale={0.04}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={nodes.Object_5.material}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={nodes.Object_7.material}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={nodes.Object_8.material}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={nodes.Object_9.material}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={nodes.Object_11.material}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={nodes.Object_13.material}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={nodes.Object_15.material}
            />
          </group>
          <group
            position={[-0.14, 1.45, 1.55]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[0.04, 0.04, 0.04]}
          >
            <mesh
              geometry={nodes.Object_17.geometry}
              material={nodes.Object_17.material}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={nodes.Object_19.material}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={nodes.Object_21.material}
            />
            <mesh
              geometry={nodes.Object_22.geometry}
              material={nodes.Object_22.material}
            />
            <mesh
              geometry={nodes.Object_23.geometry}
              material={nodes.Object_23.material}
            />
            <mesh
              geometry={nodes.Object_24.geometry}
              material={nodes.Object_24.material}
            />
            <mesh
              geometry={nodes.Object_25.geometry}
              material={nodes.Object_25.material}
            />
            <mesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
            />
            <mesh
              geometry={nodes.Object_27.geometry}
              material={nodes.Object_27.material}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={nodes.Object_28.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/iphone.gltf");
