/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
title: (FREE) iPhone 13 Pro 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.54}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.1, 1.45, -0.26]} scale={0.04}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
            <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
            <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
            <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
          </group>
          <group position={[-0.14, 1.45, 1.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
